
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

stages:
  - stage: Build
    displayName: Build App
    jobs:

      - job: XamarinCompile
        displayName: Building xamarin android

        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: 'src/Monthly Subscriptions.sln'
            feedsToUse: 'config'
            nugetConfigPath: 'src/nuget.config'

        - task: XamarinAndroid@1
          inputs:
            projectFile: src/MonthlySubscriptions/MonthlySubscriptions.Android/MonthlySubscriptions.Android.csproj
            outputDirectory: $(outputDirectory)
            configuration: '$(buildConfiguration)' 

        - publish: $(outputDirectory)
          artifact: subscriptionsAndroid
        

  - stage: AppCenterDeploy
    displayName: Deploy to App Center
    jobs:

      - job: AppCenter

        steps:

        - download: current
          artifact: subscriptionsAndroid
          patterns: '**/*Signed.apk'

        - script: ls $(Pipeline.Workspace)/subscriptionsAndroid

        - task: AppCenterDistribute@3
          inputs:
            serverEndpoint: 'My App Center'
            appSlug: 'live.neville-live.com/Monthly-Subscriptions'
            appFile: '$(Pipeline.Workspace)/subscriptionsAndroid/com.companyname.monthlysubscriptions-Signed.apk'
            symbolsOption: 'Android'
            releaseNotesOption: 'input'
            releaseNotesInput: 'The lazy developer hasn''t added any actual release notes.'
            destinationType: 'groups'
          


