
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  apkPath: subscriptionsAndroid/com.companyname.monthlysubscriptions.apk

stages:
  - stage: Build
    displayName: Build App
    jobs:

      - job: XamarinCompile
        displayName: Building xamarin android

        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: 'src/Monthly Subscriptions.sln'
            feedsToUse: 'config'
            nugetConfigPath: 'src/nuget.config'

        
        - task: android-manifest-version@1
          inputs:
            sourcePath: src/MonthlySubscriptions/MonthlySubscriptions.Android
            printFile: true
            versionCode: $(Build.BuildId)
            versionName: 1.0.$(Build.BuildId)

        - task: XamarinAndroid@1
          inputs:
            projectFile: 'src/MonthlySubscriptions/MonthlySubscriptions.Android/MonthlySubscriptions.Android.csproj'
            outputDirectory: '$(outputDirectory)'
            configuration: '$(buildConfiguration)'
            msbuildVersionOption: 'latest'

        - publish: $(outputDirectory)
          artifact: subscriptionsAndroid
        

  - stage: AppCenterDeploy
    displayName: Deploy to App Center
    jobs:

      - job: AppCenter

        steps:

        - download: current
          artifact: subscriptionsAndroid
          # patterns: $(apkPath)

        - task: AndroidSigning@3
          inputs:
            apkFiles: $(Pipeline.Workspace)/$(apkPath)
            apksignerKeystoreFile: 'subscriptions.jks'
            apksignerKeystorePassword: '$(keystore.password)'
            apksignerKeystoreAlias: 'key0'
            apksignerKeyPassword: '$(key.password)'

        - task: AppCenterDistribute@3
          inputs:
            serverEndpoint: 'My App Center'
            appSlug: 'live.neville-live.com/Monthly-Subscriptions'
            appFile: '$(Pipeline.Workspace)/$(apkPath)'
            symbolsOption: 'Android'
            releaseNotesOption: 'input'
            releaseNotesInput: 'The lazy developer hasn''t added any actual release notes.'
            destinationType: 'groups'
          


