
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

stages:
  - stage: Build
    jobs:

      - job: XamarinCompile
        displayName: Building xamarin android

        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            command: 'restore'
            restoreSolution: 'src/Monthly Subscriptions.sln'
            feedsToUse: 'config'
            nugetConfigPath: 'src/nuget.config'

        - task: XamarinAndroid@1
          inputs:
            projectFile: '**/*droid*.csproj'
            outputDirectory: '$(outputDirectory)'
            configuration: '$(buildConfiguration)' 



